name: DevSecOps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Generate Semantic Version
      id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        format: "${major}.${minor}.${patch}"
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "feat"

    - name: Print Version
      run: echo "VERSION=${{ steps.version.outputs.version }}"

    - name: Set lowercase owner
      run: |
        echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        VERSION=${{ steps.version.outputs.version }}
        docker build --no-cache \
          -t ghcr.io/$OWNER/devops:$VERSION \
          -t ghcr.io/$OWNER/devops:latest \
          -f app/Dockerfile app/

    - name: Scan Image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ghcr.io/${{ env.OWNER }}/devops:latest
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        exit-code: "0"
        args: >
          --skip-db-update
          --skip-java-db-update

    - name: Login to GHCR
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io \
          -u ${{ github.actor }} --password-stdin

    - name: Push Image to GHCR
      run: |
        VERSION=${{ steps.version.outputs.version }}
        docker push ghcr.io/$OWNER/devops:$VERSION
        docker push ghcr.io/$OWNER/devops:latest

    # âœ… START KUBERNETES FIRST
    - name: Start Minikube
      run: |
        minikube status || minikube start --driver=docker
        kubectl config use-context minikube

    - name: Create GHCR Secret in Kubernetes
      run: |
        kubectl delete secret ghcr-secret --ignore-not-found=true
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GHCR_PAT }} \
          --docker-email=dummy@example.com

    - name: Apply Kubernetes Manifests
      run: kubectl apply -f k8s/

    - name: Update Deployment Image
      run: |
        VERSION=${{ steps.version.outputs.version }}
        kubectl set image deployment/devsecops-app \
          web=ghcr.io/$OWNER/devops:$VERSION

    - name: Wait for Rollout
      run: kubectl rollout status deployment/devsecops-app
